### PR TITLE
Module 1: Portfolio set up, mobile first

### PR DESCRIPTION
**Pull request by jaredatandi**
## Portfolio set up milestone 1: mobile first
In this module, I have added the following files:
- index.html
- style.css
- README.md
- favicon images
- background SVG images

I have also done the following configurations to the repo:
- Set up Linters configuration by adding the following files:
      -  .hintrc
      -  .stylelintrc.json
- Configured GitHub actions by adding the following file in the workflow folder:
     - linters.yml

### CODE REVIEW

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @jaredatandi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, with a Pull Request without a descriptive title telling what changes are inside and without a short summary describing introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jaredatandi** [comment]
Hello, @Owusu-Desmond thank you for taking the time to review my code.
I have edited the PR message, is it now in order?

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @jaredatandi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! Please make the changes I mentioned below 😃 

- `1`- If you notice the `Welcome` text and the location of the `Hamburger` button is not correct like the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) and the size of the `Hamburger` button seems to be bigger. Please correct them 👍 
- `2`- The `position` and `thickness` of your main text(`"Hey there. I’m Jared. I’m a software developer"`) part is not the same as [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468), please go to [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) and check them from your `template` and correct the required style mistakes 👍 
- `3`- Your `class="Support-text"` class text position and thickness are not the same as [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988), please go to [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988) and check them from your `template` and correct the required style mistakes 👍 
- `4`- I think your `social icons` **position**, **size** and **color** are not like [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988) so please style it like [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A988). These changes are made with your benefit in mind, and I trust you will find them easy to implement 😄 

image
 
- [ ] [REQUIRED] Please change the `p` tag on lines `43` to `46` in your **"index.html"** file to `h1` tag because `p` tag is not considered semantic in this situation 👍 

image

- [ ] [REQUIRED] Good job so far 👍  Please the list of `icons` should use a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag) 😃 

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaredatandi** [comment]
Hello @mukhammadrizooff Thank you for your detailed review. Yeah, those were really easy to implement for a beginner haha. 


Anyway, I have implemented the suggestion. Could you be kind enough to do a quick sweep and let me know if there is something I am missing? 

The changes are on this branch [Updated-style](https://github.com/jaredatandi/Portfolio/tree/Updated-style)
Thank you in advance.

**Pull request merged**
